// Species (DEX), moves (MOVES) and learnsets live in js/dex.js (generated by tools/build-data.js).
// Moves use the Gen 4+ physical / special split (move.cat: 'P' physical, 'S' special, 'X' status).

const TYPE_COLORS = {
  NORMAL: '#a8a878', FIRE: '#f08030', WATER: '#6890f0', ELECTRIC: '#f8d030', GRASS: '#78c850',
  ICE: '#98d8d8', FIGHTING: '#c03028', POISON: '#a040a0', GROUND: '#e0c068', FLYING: '#a890f0',
  PSYCHIC: '#f85888', BUG: '#a8b820', ROCK: '#b8a038', GHOST: '#705898', DRAGON: '#7038f8',
  DARK: '#705848', STEEL: '#b8b8d0', FAIRY: '#ee99ac', '???': '#68a090',
};
const TYPES = Object.keys(TYPE_COLORS).filter(t => t !== '???');

// Gen 6+ chart (Fairy added; Steel no longer resists Ghost / Dark).
const TYPE_CHART = {
  NORMAL: { ROCK: .5, GHOST: 0, STEEL: .5 },
  FIRE: { FIRE: .5, WATER: .5, GRASS: 2, ICE: 2, BUG: 2, ROCK: .5, DRAGON: .5, STEEL: 2 },
  WATER: { FIRE: 2, WATER: .5, GRASS: .5, GROUND: 2, ROCK: 2, DRAGON: .5 },
  ELECTRIC: { WATER: 2, ELECTRIC: .5, GRASS: .5, GROUND: 0, FLYING: 2, DRAGON: .5 },
  GRASS: { FIRE: .5, WATER: 2, GRASS: .5, POISON: .5, GROUND: 2, FLYING: .5, BUG: .5, ROCK: 2, DRAGON: .5, STEEL: .5 },
  ICE: { FIRE: .5, WATER: .5, GRASS: 2, ICE: .5, GROUND: 2, FLYING: 2, DRAGON: 2, STEEL: .5 },
  FIGHTING: { NORMAL: 2, ICE: 2, POISON: .5, FLYING: .5, PSYCHIC: .5, BUG: .5, ROCK: 2, GHOST: 0, DARK: 2, STEEL: 2, FAIRY: .5 },
  POISON: { GRASS: 2, POISON: .5, GROUND: .5, ROCK: .5, GHOST: .5, STEEL: 0, FAIRY: 2 },
  GROUND: { FIRE: 2, ELECTRIC: 2, GRASS: .5, POISON: 2, FLYING: 0, BUG: .5, ROCK: 2, STEEL: 2 },
  FLYING: { ELECTRIC: .5, GRASS: 2, FIGHTING: 2, BUG: 2, ROCK: .5, STEEL: .5 },
  PSYCHIC: { FIGHTING: 2, POISON: 2, PSYCHIC: .5, DARK: 0, STEEL: .5 },
  BUG: { FIRE: .5, GRASS: 2, FIGHTING: .5, POISON: .5, FLYING: .5, PSYCHIC: 2, GHOST: .5, DARK: 2, STEEL: .5, FAIRY: .5 },
  ROCK: { FIRE: 2, ICE: 2, FIGHTING: .5, GROUND: .5, FLYING: 2, BUG: 2, STEEL: .5 },
  GHOST: { NORMAL: 0, PSYCHIC: 2, GHOST: 2, DARK: .5 },
  DRAGON: { DRAGON: 2, STEEL: .5, FAIRY: 0 },
  DARK: { FIGHTING: .5, PSYCHIC: 2, GHOST: 2, DARK: .5, FAIRY: .5 },
  STEEL: { FIRE: .5, WATER: .5, ELECTRIC: .5, ICE: 2, ROCK: 2, STEEL: .5, FAIRY: 2 },
  FAIRY: { FIRE: .5, FIGHTING: 2, POISON: .5, DRAGON: 2, DARK: 2, STEEL: .5 },
  '???': {},
};

function typeEffectiveness(moveType, defTypes) {
  let m = 1;
  for (const t of defTypes) {
    const row = TYPE_CHART[moveType] || {};
    if (row[t] !== undefined) m *= row[t];
  }
  return m;
}

// Hand-tuned sets for the original FireRed rival battle.
const TEAMS = {
  player: [
    { species: 'CHARIZARD', level: 52, gender: 'M', moves: ['FLAMETHROWER', 'DRAGONCLAW', 'AERIALACE', 'SWORDSDANCE'] },
    { species: 'BLASTOISE', level: 50, gender: 'M', moves: ['SURF', 'ICEBEAM', 'RAINDANCE', 'PROTECT'] },
    { species: 'VENUSAUR', level: 50, gender: 'F', moves: ['RAZORLEAF', 'SLUDGEBOMB', 'SLEEPPOWDER', 'LEECHSEED'] },
    { species: 'PIKACHU', level: 50, gender: 'M', moves: ['THUNDERBOLT', 'QUICKATTACK', 'THUNDERWAVE', 'DOUBLETEAM'] },
    { species: 'SNORLAX', level: 50, gender: 'M', moves: ['BODYSLAM', 'EARTHQUAKE', 'SHADOWBALL', 'REST'] },
    { species: 'LAPRAS', level: 50, gender: 'F', moves: ['ICEBEAM', 'THUNDERBOLT', 'BODYSLAM', 'CONFUSERAY'] },
  ],
  foe: [
    { species: 'PIDGEOT', level: 50, gender: 'M', moves: ['AERIALACE', 'DOUBLEEDGE', 'SANDATTACK', 'QUICKATTACK'] },
    { species: 'ALAKAZAM', level: 52, gender: 'M', moves: ['PSYCHIC', 'FIREPUNCH', 'RECOVER', 'CALMMIND'] },
    { species: 'RHYDON', level: 51, gender: 'M', moves: ['EARTHQUAKE', 'ROCKSLIDE', 'MEGAHORN', 'TAKEDOWN'] },
    { species: 'GYARADOS', level: 51, gender: 'M', moves: ['HYDROPUMP', 'DRAGONDANCE', 'EARTHQUAKE', 'HYPERBEAM'] },
    { species: 'ARCANINE', level: 52, gender: 'M', moves: ['FLAMETHROWER', 'EXTREMESPEED', 'CRUNCH', 'WILLOWISP'] },
    { species: 'EXEGGUTOR', level: 53, gender: 'M', moves: ['GIGADRAIN', 'PSYCHIC', 'STUNSPORE', 'EGGBOMB'] },
  ],
};

const ITEMS = {
  'POKé BALL': { desc: 'A tool for catching wild POKéMON.', kind: 'ball', rate: 1, wildOnly: true },
  'GREAT BALL': { desc: 'A good BALL with a higher catch rate than a POKé BALL.', kind: 'ball', rate: 1.5, wildOnly: true },
  'ULTRA BALL': { desc: 'A better BALL with a higher catch rate than a GREAT BALL.', kind: 'ball', rate: 2, wildOnly: true },
  'MASTER BALL': { desc: 'The best BALL. It catches any wild POKéMON without fail.', kind: 'ball', rate: 255, wildOnly: true },
  'POTION': { desc: 'Restores the HP of a POKéMON by 20 points.', kind: 'heal', amount: 20 },
  'SUPER POTION': { desc: 'Restores the HP of a POKéMON by 50 points.', kind: 'heal', amount: 50 },
  'HYPER POTION': { desc: 'Restores the HP of a POKéMON by 200 points.', kind: 'heal', amount: 200 },
  'MAX POTION': { desc: 'Fully restores the HP of a POKéMON.', kind: 'heal', amount: 9999 },
  'FULL RESTORE': { desc: 'Fully restores HP and heals any status problem.', kind: 'full' },
  'FULL HEAL': { desc: 'Heals all the status problems of one POKéMON.', kind: 'cure' },
  'REVIVE': { desc: 'Revives a fainted POKéMON with half its max HP.', kind: 'revive', frac: 0.5 },
  'MAX REVIVE': { desc: 'Revives a fainted POKéMON with all its HP.', kind: 'revive', frac: 1 },
  'X ATTACK': { desc: 'Raises the ATTACK stat of the active POKéMON.', kind: 'x', stat: 'atk' },
  'X DEFENSE': { desc: 'Raises the DEFENSE stat of the active POKéMON.', kind: 'x', stat: 'def' },
  'X SPEED': { desc: 'Raises the SPEED stat of the active POKéMON.', kind: 'x', stat: 'spe' },
  'X SPECIAL': { desc: 'Raises the SP. ATK stat of the active POKéMON.', kind: 'x', stat: 'spa' },
};

const STAT_NAMES = { atk: 'ATTACK', def: 'DEFENSE', spa: 'SP. ATK', spd: 'SP. DEF', spe: 'SPEED', acc: 'accuracy', eva: 'evasiveness' };
const STATUS_LABEL = { par: 'PAR', slp: 'SLP', psn: 'PSN', tox: 'PSN', brn: 'BRN', frz: 'FRZ' };

function expForLevel(growth, n) {
  if (n <= 1) return 0;
  const n3 = n ** 3;
  switch (growth) {
    case 'fast': return Math.floor(4 * n3 / 5);
    case 'mf': return n3;
    case 'slow': return Math.floor(5 * n3 / 4);
    case 'erratic':
      if (n <= 50) return Math.floor(n3 * (100 - n) / 50);
      if (n <= 68) return Math.floor(n3 * (150 - n) / 100);
      if (n <= 98) return Math.floor(n3 * Math.floor((1911 - 10 * n) / 3) / 500);
      return Math.floor(n3 * (160 - n) / 100);
    case 'fluct':
      if (n <= 15) return Math.floor(n3 * (Math.floor((n + 1) / 3) + 24) / 50);
      if (n <= 36) return Math.floor(n3 * (n + 14) / 50);
      return Math.floor(n3 * (Math.floor(n / 2) + 32) / 50);
    default: return Math.max(0, Math.floor(1.2 * n3 - 15 * n ** 2 + 100 * n - 140));
  }
}

function spritePathFor(species, back) {
  return `assets/sprites/${species.id}${back ? '_back' : ''}.${species.spr === 'png' ? 'png' : 'gif'}`;
}
